osx_image: xcode7.3
language: objective-c
xcode_project: Graph.xcodeproj
xcode_scheme: Graph
before_install:
    - gem install xcpretty
git:
   depth: 3

script:
    - xcodebuild -scheme Graph -project Graph.xcodeproj -sdk iphonesimulator -destination 'OS=9.3,name=iPhone 6s Plus' build test | xcpretty
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'Graph'
